Optimization Under Uncertainty
hippylib/hippyflow pull request #18
Opened 2022-11-05 18:42 UTC by tomoleary

Adding support for optimization problems, where there is an additional paramter `z` that is optimized in expectation over the distribution of parameter `m`, e.g., the prior

2023-03-28 00:22 UTC, tomoleary commented
Should we add evaluation helper arrays to `Observable` classes in order to avoid constant need for new allocations?

2023-06-13 15:59 UTC, dc-luo requested changes

2023-06-13 15:59 UTC, dc-luo commented on hippyflow/modeling/activeSubspaceProjector.py
> +			control_rank = min(self.parameters['jacobian_rank'],output_dimension,control_dimension)
Should this be `self.parameters['control_jacobian_rank']`

2023-06-13 15:59 UTC, dc-luo commented on hippyflow/modeling/observable.py
>  		elif component == 3:
I think `CONTROL` is defined in this file. Let's use that instead of 3

2023-06-14 13:46 UTC, tomoleary commented on hippyflow/modeling/activeSubspaceProjector.py
> +			control_rank = min(self.parameters['jacobian_rank'],output_dimension,control_dimension)
Thanks!

2023-06-14 13:48 UTC, dc-luo approved these changes

2023-06-14 14:23 UTC, merged